### ISSUE TITLE
[BUG] - Elements on page don't load unless hovered over

### ISSUE THREAD

**Issue by kozlowsm** [kozlowsm/LaunchPadv2.0#16]
Several launch containers load but do not show content unless the container is clicked on or the area where the arrow button is hovered over.

![screen shot 2019-01-12 at 8 49 31 am](https://user-images.githubusercontent.com/22461040/51074038-bcf25d00-1647-11e9-8587-c6cc065c5747.png)

**Comment by cberry216** [comment]
Chrome seems to refuse to render some text that is hidden by the style "overflow: hidden". Safari and Firefox have no problem.

**Comment by cberry216** [comment]
Also the text that doesn't get rendered is always different.

**Comment by cberry216** [comment]
If you try select the text within a launch div, the text for the entire div shows up (i.e. Chrome not rendering the text).

**Comment by cberry216** [comment]
By using the `-webkit-transform: scale3d(1, 1, 1);` style to `div.launches`, this issue has been corrected.
